### ISSUE TITLE
Nuxt3へ移行し、blog-udcxx-meをv1とする

### ISSUE THREAD

**Issue by udcxx** [udcxx/blog-udcxx-me#25]
## 現状

[2023年末にVue2のサポートが終了する](https://nuxt.com/blog/vision-2023)ため、Vue2に対応しているNuxt2のサポートも同時に終了する。現在使用しているフレームワークがNuxt2であるため、2023年末までにNuxt3へ移行する必要がある。

## 対応方法

Nuxt3へ移行を行う。同時に、以下の項目についても改修・変更する。

- [x] 記事の管理を、content v2で行うように変更する
- [x] TOPページのデザインを新デザインに移行する
- [ ] [ブランチを整理する · Issue #26 · udcxx/blog-udcxx-me](https://github.com/udcxx/blog-udcxx-me/issues/26)
- [x] [タグを整理する · Issue #27 · udcxx/blog-udcxx-me](https://github.com/udcxx/blog-udcxx-me/issues/27)
- [x] [絵文字用のフォントを導入する · Issue #28 · udcxx/blog-udcxx-me](https://github.com/udcxx/blog-udcxx-me/issues/28)
- [ ] [Nuxt3でGA4を動作させる · Issue #29 · udcxx/blog-udcxx-me](https://github.com/udcxx/blog-udcxx-me/issues/29)
- [x] [画像のloading属性をlazyにする · Issue #31 · udcxx/blog-udcxx-me](https://github.com/udcxx/blog-udcxx-me/issues/31)
- [ ] ~~[次世代フォーマットでの画像の配信 · Issue #32 · udcxx/blog-udcxx-me](https://github.com/udcxx/blog-udcxx-me/issues/32)~~ 保留する https://github.com/udcxx/blog-udcxx-me/issues/32#issuecomment-1590458489

**Comment by udcxx** [comment]
これまでバージョン管理してなかったのに、急に v2 にするのもアレなので、今回のバージョンアップで v1.0.0 からカウントを始める。
